services:

  # Python backend container
  python_service:
    container_name: container-python
    networks:
      - default
    image: dsci-cap-img-python:latest
    build:    # Fall back to building from scratch if image does not exist
      context: .
      dockerfile: Dockerfile.python

  # Blazor server container, exposes port for HTTP and REST
  blazor_service:
    container_name: container-blazor
    networks:
      - default
    image: dsci-cap-img-blazor:latest
    build:    # Fall back to building from scratch if image does not exist
      context: .
      dockerfile: Dockerfile.blazor
    environment:
      - DOTNET_ENVIRONMENT=Docker
    ports:
      - "5055:5055"


  # Meta-service to orchestrate all DB containers at once
  databases_service:
    container_name: container-databases
    image: alpine   # extremely small OS
    command: ["sleep", "infinity"]
    depends_on:
      - mysql_service
      - postgres_service  # redundant with mysql but no downside - use makefile to launch only one
      - mongo_service
      - neo4j_service
      

  # MySQL container, volume persists data, port optional
  mysql_service:
    container_name: container-mysql
    networks:      # DB containers will listen on this hostname for convenient access
      default:     # attach to our docker network
        aliases:   # does not replace service_name
          - databases_service
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password   # not used, but required by MySQL installation
      - MYSQL_DATABASE=${DB_NAME}
      #- MYSQL_USER=${MYSQL_USERNAME}   # cannot be root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Postgres container, volume persists data, port optional
  postgres_service:
    container_name: container-postgres
    networks:      # DB containers will listen on this hostname for convenient access
      default:     # attach to our docker network
        aliases:   # does not replace service_name
          - databases_service
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MongoDB container, volume persists data, port optional
  mongo_service:
    container_name: container-mongo
    networks:      # DB containers will listen on this hostname for convenient access
      default:     # attach to our docker network
        aliases:   # does not replace service_name
          - databases_service
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Neo4j container, exposes HTTP and Bolt ports for UI and app connections
  neo4j_service:
    container_name: container-neo4j
    networks:      # DB containers will listen on this hostname for convenient access
      default:     # attach to our docker network
        aliases:   # does not replace service_name
          - databases_service
    image: neo4j:5
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}   # format: "username/password"
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"   # HTTP web UI
      - "7687:7687"   # Bolt protocol for queries


volumes:
  mysql_data:
  postgres_data:
  mongo_data:
  neo4j_data:


networks:  # declare our docker network globally
  default:
    name: capstone_default    # otherwise docker will auto-generate the name as "<parent_folder> + _default"