name: Build Job
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  update-images:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload_images.outputs.artifact-id }}
      secrets: ${{ steps.upload_secrets.outputs.artifact-id }}
    steps:

      # Speed up build process with Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      # 1. Start from a checkpoint to speed up the build process.
      # Automatically retagged as "dev"
      - name: Pull last successful Docker images
        run: |
          echo "🔹 Trying private GHCR images..."
          if make docker-pull-dev; then
            make docker-retag-dev-local DEVTAG=${{ inputs.image-tag }}
            echo "✅ Pulled from private namespace."
          else
            echo "⚠️ Private pull failed, trying public images..."
            if make docker-pull; then
              echo "✅ Pulled from public namespace."
            else
              echo "🚫 No cached images found — continuing with rebuild."
            fi
          fi


      # 2. Set up environment with latest source code
      - name: Download code from repository
        uses: actions/checkout@v4

      - name: Create secrets files with fake credentials
        run: |
          make env-dummy OUT=".env"
          make appsettings-dummy OUT="web-app/BlazorApp/appsettings.json" ENVF=".env"

      - name: Upload dummy secrets artifacts
        id: upload_secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets-artifacts
          path: |
            .env
            web-app/BlazorApp/appsettings.json
          retention-days: 1

      
      # 3. Update the local Docker images with latest code
      # This creates the images with baked-in .env and appsettings.json files.
      # gha = GitHub Actions, matches ANY suitable image layer regardless of image name.
      - name: Build new Docker images
        run: make docker-build-dev CACHE_ARGS="--cache-from type=gha --cache-to type=gha,mode=max"


      # 4. Send these images over to the main CI/CD workflow
      # Faster than uploading + downloading with GHCR
      - name: Upload images artifact
        id: upload_images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-ci
          path: docker-images-ci.tar
          retention-days: 1


