name: Docker CD - Deploy

on:
  push:
    branches: [ main ]

concurrency:  # Prevent multiple runs on rapid pushes
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build latest Docker images
        run: make docker-build

      - name: Create .env file with fake credentials
        run: make env-dummy

      - name: Run all containers and tests
        run: make docker-all-tests

      - name: Publish Docker images to GHCR
        if: success()
        run: make docker-publish

      - name: Cleanup
        if: always()   # Runs even if previous steps fail
        run: make docker-full-reset || true  # Cleanup failures wont fail the workflow
