name: Push Job
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      private-namespace:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  push-images-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.private-namespace }} with image tag ${{ inputs.image-tag }}"

      # 1. Download artifacts
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: .

      - name: Load Docker images
        run: docker load < docker-images-ci.tar

      # 2. Upload images to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push images to a private GHCR namespace
        run: make docker-push-dev DEVTAG=${{ inputs.image-tag }}

