name: Publish Job
on:
  workflow_call:
    inputs:
      public-namespace:
        required: true
        type: string

jobs:
  push-images-prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to '${{ inputs.public-namespace }}' with image tag 'latest'"

      # Initial setup
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Speed up rebuild by starting from the last public checkpoint
      - name: Pull last public images for cache
        run: make docker-pull || true   # Otherwise start from scratch

      - name: Build and publish safe production images
        run: make docker-publish

